---
- name: Clone yas repo
  git:
    repo={{ yas_repo }}
    dest={{ local_repository }}
    version={{ yas_repo_version }}
    accept_hostkey=yes
    update={{ yas_repo_update }}
  check_mode: no

- name: Install yas
  pip:
    name={{ local_repository }}
    state=latest
    executable={{ pip_executable }}

- name: Install yas systemd service
  copy:
    src={{ local_repository }}/yas.service
    remote_src=yes
    dest=/etc/systemd/system/yas.service
  when: ansible_service_mgr == 'systemd'

- name: Activate yas systemd service
  systemd:
    name=yas
    daemon_reload=yes
    enabled=yes
    state=started
  when: ansible_service_mgr == 'systemd'
