---
- name: Clone yas repo
  git:
    repo={{ yas_repo }}
    dest={{ local_repository }}
    version={{ yas_repo_version }}
    accept_hostkey=yes
    update={{ yas_repo_update }}
  check_mode: no
  notify: restart yas

- name: Install yas
  pip:
    name={{ local_repository }}
    state=latest
    executable={{ pip_executable }}

- name: Install yas systemd service
  copy:
    src={{ local_repository }}/yas.service
    remote_src=yes
    dest=/etc/systemd/system/yas.service
  when: ansible_service_mgr == 'systemd'
  notify: restart yas

- name: Activate yas systemd service
  systemd:
    name=yas
    daemon_reload=yes
    state=started
    enabled=yes
  when: ansible_service_mgr == 'systemd'

- name: Copy yas config
  template:
    src: yas.yml.j2
    dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/yas.yml
  notify: restart yas

- name: Install handler packages
  command: "{{ pip_executable }} install {{ item }}"
  with_items: "{{ handler_packages }}"
  when: handler_packages

- name: Copy handler configs from vars
  copy:
    content: "{{ item.content | to_nice_yaml }}"
    dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/{{ item.name }}
  with_items: "{{ handler_configs }}"
  when: handler_configs
  notify: restart yas

- name: Copy handler configs as files
  copy:
    src: custom/{{ item }}
    dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/{{ item }}
  with_items: "{{ handler_config_files }}"
  when: handler_config_files
  notify: restart yas
