---
- name: Clone yas repo
  git:
    repo=https://github.com/schlueter/yas.git
    dest={{ local_repository }}
    update=no
    accept_hostkey=yes

- name: Install yas
  pip:
    name={{ local_repository }}
    state=latest
    executable={{ pip_executable }}


- name: Set slack_app_token if provided
  lineinfile:
    dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/yas.yml
    regexp: '^slack_app_token: '
    line: "slack_app_token: {{ slack_app_token }}"
  when: slack_app_token is defined

- name: Install yas systemd service
  copy:
    src={{ local_repository }}/yas.service
    remote_src=yes
    dest=/etc/systemd/system/yas.service
  when: ansible_service_mgr == 'systemd'

- name: Activate yas systemd service
  systemd:
    name=yas
    daemon_reload=yes
    enabled=yes
    state=started
  when: ansible_service_mgr == 'systemd'
