---
- hosts: yas
  gather_facts: no
  become: yes
  tasks:
    - name: apt-get update
      raw: apt-get update -qq
    - name: Install python 2.7
      raw: apt-get install -qq python-minimal

- hosts: yas
  gather_facts: yes
  become: yes
  roles: [ yas ]
  tasks:
    - name: Copy yas config
      template:
        src: yas.yml.j2
        dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/yas.yml

    - name: Copy handler configs from vars
      copy:
        content: "{{ item.content | to_nice_yaml }}"
        dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/{{ item.name }}
      with_items: "{{ handler_configs }}"
      when: handler_configs

    - name: Copy handler configs as files
      copy:
        src: custom/{{ item }}
        dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/{{ item }}
      with_items: "{{ handler_config_files }}"
      when: handler_config_files

    - name: Install handler packages
      command: "{{ pip_executable }} install {{ item }}"
      with_items: "{{ handler_packages }}"
      when: handler_packages
