---
- hosts: yas
  gather_facts: no
  tasks:
    - name: apt-get update
      raw: apt-get update -qq
    - name: Install python 2.7
      raw: apt-get install -qq python-minimal

- hosts: yas
  gather_facts: yes
  become: yes
  roles: [ yas ]
  tasks:
    - name: Put some useful things in bash history
      copy:
        dest: /home/ubuntu/.bash_history
        owner: ubuntu
        group: ubuntu
        content: |
          pip install -U /vagrant
          sudo systemctl restart yas
          journalctl -xaefu yas
          cp /vagrant/yas.yml /usr/local/lib/pyenv/versions/3.6.0/etc/yas/
          sudo chmod -R 2775 /usr/local/lib/pyenv/

    - name: Copy yas config
      template:
        src: yas.yml.j2
        dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/yas.yml

    - name: Copy handler configs
      copy:
        content: "{{ item.content | to_nice_yaml }}"
        dest: /usr/local/lib/pyenv/versions/3.6.0/etc/yas/{{ item.name }}.yml
      with_items: "{{ handler_configs }}"
      when: handler_configs

    - name: Install handler packages
      pip:
        name={{ item }}
        state=latest
        executable={{ pip_executable }}
      with_items: "{{ handler_packages }}"
      when: handler_packages
